name: Deploy website
on: 
  push:
    branches: 
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skipci]')"
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      - name: Make executable
        run: "chmod +x ./_build.sh"
      # Runs a set of commands using the runners shell
      - name: Run docker for R 
        uses: docker://larsvilhuber/ideahandbook:latest
        with:
          args: "/github/workspace/_build.sh"
          
          
      # send it to gh-pages
      # We use a personal token to allow for posting despite branch controls - see https://github.com/peaceiris/actions-gh-pages for parameters
      # We also use a *beta* feature to post to a particular destination_dir. 
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.0-8
        with:
           github_token: ${{ secrets.PUBLISH_TOKEN_LARS }}
           publish_dir: _book
           user_name: 'Github Action Bot'
           user_email: 'lars.vilhuber@cornell.edu'
           destination_dir: testing
           publish_branch: published_version 
           keep_files: true
