name: Set version and redirect
on: 
  push:
    branches: 
      - published_version
jobs:
  set-version:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skipci]')"
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2 
        with:
          ref: published_version
      - name: Make executable
        run: |
          # make executable
          chmod +x ./_process/set_version.sh
          # run it
          ./_process/set_version.sh
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add index.html
          git commit -m "[skipci] Set version for redirect"
          git push
